[package]
name = "holiday-chat-service"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "0.5.0-rc.1"
rocket_cors = "0.5.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
csv = "1.1"
